-- TYPE C: additive AI audit enum values only. No business data migration.
ALTER TYPE "AIAuditEventType" ADD VALUE 'TOOL_EXECUTION_STARTED';
ALTER TYPE "AIAuditEventType" ADD VALUE 'TOOL_EXECUTION_COMPLETED';
ALTER TYPE "AIAuditEventType" ADD VALUE 'TOOL_EXECUTION_FAILED';
ALTER TYPE "AIAuditEventType" ADD VALUE 'TOOL_PERMISSION_DENIED';
ALTER TYPE "AIAuditEventType" ADD VALUE 'TOOL_INPUT_INVALID';
ALTER TYPE "AIAuditEventType" ADD VALUE 'TOOL_OUTPUT_INVALID';
