import type { WatchBrandAbbrev, WatchKnowledgeEntry } from './types';
import { WATCH_KNOWLEDGE_VERSION } from './types';

export { WATCH_KNOWLEDGE_VERSION };

/** Dealer abbreviations → canonical brand + inventory brand tokens. */
export const BRAND_ABBREVIATIONS: WatchBrandAbbrev[] = [
  {
    abbrev: 'AP',
    canonicalBrand: 'Audemars Piguet',
    inventoryBrandTokens: ['AP', 'Audemars Piguet', 'Audemars', 'AUDEMARS PIGUET'],
  },
  {
    abbrev: 'PP',
    canonicalBrand: 'Patek Philippe',
    inventoryBrandTokens: ['PP', 'Patek', 'Patek Philippe', 'PATEK', 'PATEK PHILIPPE'],
  },
  {
    abbrev: 'VC',
    canonicalBrand: 'Vacheron Constantin',
    inventoryBrandTokens: ['VC', 'Vacheron', 'Vacheron Constantin', 'VACHERON'],
  },
  {
    abbrev: 'JLC',
    canonicalBrand: 'Jaeger-LeCoultre',
    inventoryBrandTokens: ['JLC', 'Jaeger', 'Jaeger-LeCoultre', 'Jaeger LeCoultre'],
  },
  {
    abbrev: 'RM',
    canonicalBrand: 'Richard Mille',
    inventoryBrandTokens: ['RM', 'Richard Mille', 'RICHARD MILLE'],
  },
  {
    abbrev: 'IWC',
    canonicalBrand: 'IWC',
    inventoryBrandTokens: ['IWC'],
  },
];

/**
 * High-value market nicknames. Ambiguous nicknames are flagged.
 * Prefer established secondary-market usage only.
 */
export const WATCH_KNOWLEDGE_ENTRIES: WatchKnowledgeEntry[] = [
  // ── Rolex GMT / Sub / Daytona ───────────────────────────────────────────
  {
    id: 'rolex-gmt-pepsi-blro',
    canonicalBrand: 'Rolex',
    family: 'GMT-Master II',
    canonicalModel: 'GMT-Master II Pepsi',
    references: ['126710BLRO', '1675', '16710'],
    nicknames: ['Pepsi'],
    aliases: ['GMT Pepsi', 'Rolex Pepsi', 'BLRO'],
    descriptors: ['red blue bezel'],
  },
  {
    id: 'rolex-gmt-coke',
    canonicalBrand: 'Rolex',
    family: 'GMT-Master II',
    canonicalModel: 'GMT-Master II Coke',
    references: ['16710', '16760'],
    nicknames: ['Coke'],
    aliases: ['GMT Coke', 'Rolex Coke'],
    descriptors: ['black red bezel'],
  },
  {
    id: 'rolex-gmt-batman-blnr',
    canonicalBrand: 'Rolex',
    family: 'GMT-Master II',
    canonicalModel: 'GMT-Master II Batman',
    references: ['126710BLNR'],
    nicknames: ['Batman'],
    aliases: ['GMT Batman', 'Rolex Batman', 'BLNR'],
    descriptors: ['black blue bezel'],
  },
  {
    id: 'rolex-gmt-batgirl',
    canonicalBrand: 'Rolex',
    family: 'GMT-Master II',
    canonicalModel: 'GMT-Master II Batgirl',
    references: ['126710BLNR'],
    nicknames: ['Batgirl'],
    aliases: ['GMT Batgirl', 'Rolex Batgirl'],
    descriptors: ['jubilee batman'],
  },
  {
    id: 'rolex-gmt-bruce-wayne',
    canonicalBrand: 'Rolex',
    family: 'GMT-Master II',
    canonicalModel: 'GMT-Master II Bruce Wayne',
    references: ['126710GRNR'],
    nicknames: ['Bruce Wayne', 'Bruce Wayn'],
    aliases: ['GMT Bruce Wayne', 'Rolex Bruce Wayne', 'GRNR'],
    descriptors: ['grey black bezel'],
  },
  {
    id: 'rolex-gmt-sprite',
    canonicalBrand: 'Rolex',
    family: 'GMT-Master II',
    canonicalModel: 'GMT-Master II Sprite',
    references: ['126720VTNR'],
    nicknames: ['Sprite', 'Lefty'],
    aliases: ['GMT Sprite', 'Rolex Sprite', 'VTNR'],
    descriptors: ['green black lefty'],
  },
  {
    id: 'rolex-sub-hulk',
    canonicalBrand: 'Rolex',
    family: 'Submariner',
    canonicalModel: 'Submariner Hulk',
    references: ['116610LV'],
    nicknames: ['Hulk'],
    aliases: ['Sub Hulk', 'Rolex Hulk'],
    descriptors: ['green dial bezel'],
  },
  {
    id: 'rolex-sub-starbucks',
    canonicalBrand: 'Rolex',
    family: 'Submariner',
    canonicalModel: 'Submariner Starbucks',
    references: ['126610LV'],
    nicknames: ['Starbucks', 'Kermit'],
    aliases: ['Sub Starbucks', 'Rolex Starbucks', 'Rolex Kermit'],
    descriptors: ['green bezel black dial'],
  },
  {
    id: 'rolex-yacht-rootbeer',
    canonicalBrand: 'Rolex',
    family: 'Yacht-Master',
    canonicalModel: 'Yacht-Master Root Beer',
    references: ['126621', '116621'],
    nicknames: ['Root Beer', 'Rootbeer'],
    aliases: ['Yacht Master Root Beer', 'Rolex Root Beer'],
  },
  {
    id: 'rolex-smurf',
    canonicalBrand: 'Rolex',
    family: 'Submariner',
    canonicalModel: 'Submariner Smurf',
    references: ['116619LB'],
    nicknames: ['Smurf'],
    aliases: ['Sub Smurf', 'Rolex Smurf'],
    descriptors: ['blue gold'],
  },
  {
    id: 'rolex-cookie-monster',
    canonicalBrand: 'Rolex',
    family: 'Submariner',
    canonicalModel: 'Submariner Cookie Monster',
    references: ['116619LB'],
    nicknames: ['Cookie Monster'],
    aliases: ['Rolex Cookie Monster'],
    descriptors: ['blue dial platinum'],
    ambiguousNickname: true,
  },
  {
    id: 'rolex-daytona-panda',
    canonicalBrand: 'Rolex',
    family: 'Daytona',
    canonicalModel: 'Daytona Panda',
    references: ['116500LN', '126500LN'],
    nicknames: ['Panda'],
    aliases: ['Daytona Panda', 'Rolex Panda', 'Ceramic Panda'],
    descriptors: ['white dial black subdials'],
    ambiguousNickname: true,
  },
  {
    id: 'rolex-daytona-paul-newman',
    canonicalBrand: 'Rolex',
    family: 'Daytona',
    canonicalModel: 'Daytona Paul Newman',
    references: ['6263', '6265', '6239'],
    nicknames: ['Paul Newman'],
    aliases: ['PN Daytona', 'Rolex Paul Newman'],
  },
  {
    id: 'rolex-daytona-john-mayer',
    canonicalBrand: 'Rolex',
    family: 'Daytona',
    canonicalModel: 'Daytona John Mayer',
    references: ['116518LN'],
    nicknames: ['John Mayer'],
    aliases: ['Rolex John Mayer', 'Meteorite Daytona'],
  },
  {
    id: 'rolex-airking-pikachu',
    canonicalBrand: 'Rolex',
    family: 'Air-King',
    canonicalModel: 'Air-King Pikachu',
    references: ['116900'],
    nicknames: ['Pikachu'],
    aliases: ['Rolex Pikachu', 'Air King Pikachu'],
    descriptors: ['yellow black'],
  },
  {
    id: 'rolex-explorer-polar',
    canonicalBrand: 'Rolex',
    family: 'Explorer II',
    canonicalModel: 'Explorer II Polar',
    references: ['226570', '216570'],
    nicknames: ['Polar'],
    aliases: ['Explorer Polar', 'Rolex Polar'],
    descriptors: ['white dial'],
  },
  {
    id: 'rolex-deepsea-james-cameron',
    canonicalBrand: 'Rolex',
    family: 'Deepsea',
    canonicalModel: 'Deepsea James Cameron',
    references: ['126660', '136660'],
    nicknames: ['James Cameron'],
    aliases: ['D-Blue', 'Rolex James Cameron'],
  },
  {
    id: 'rolex-milgauss-gvy',
    canonicalBrand: 'Rolex',
    family: 'Milgauss',
    canonicalModel: 'Milgauss',
    references: ['116400GV'],
    nicknames: ['Bluesy'],
    aliases: ['Milgauss GV', 'Green Crystal'],
    ambiguousNickname: true,
  },
  {
    id: 'rolex-gmt-sprite-family',
    canonicalBrand: 'Rolex',
    family: 'GMT-Master II',
    nicknames: [],
    aliases: ['GMT', 'GMT Master', 'GMT-Master', 'GMT-Master II', 'GMT Master II'],
  },
  {
    id: 'rolex-daytona-family',
    canonicalBrand: 'Rolex',
    family: 'Daytona',
    nicknames: [],
    aliases: ['Daytona', 'Cosmograph'],
  },
  {
    id: 'rolex-sub-family',
    canonicalBrand: 'Rolex',
    family: 'Submariner',
    nicknames: [],
    aliases: ['Sub', 'Submariner', 'Submariner Date'],
  },

  // ── Audemars Piguet ─────────────────────────────────────────────────────
  {
    id: 'ap-roo-elephant',
    canonicalBrand: 'Audemars Piguet',
    family: 'Royal Oak Offshore',
    canonicalModel: 'Royal Oak Offshore Elephant',
    references: ['26238ST', '26238OK'],
    nicknames: ['Elephant'],
    aliases: ['AP Elephant', 'ROO Elephant', 'Royal Oak Offshore Elephant', 'Elephant AP'],
    descriptors: ['grey textured dial'],
  },
  {
    id: 'ap-safari',
    canonicalBrand: 'Audemars Piguet',
    family: 'Royal Oak Offshore',
    canonicalModel: 'Royal Oak Offshore Safari',
    nicknames: ['Safari'],
    aliases: ['AP Safari', 'ROO Safari'],
    descriptors: ['khaki'],
  },
  {
    id: 'ap-ro-family',
    canonicalBrand: 'Audemars Piguet',
    family: 'Royal Oak',
    nicknames: [],
    aliases: ['RO', 'Royal Oak', 'Jumbo'],
  },
  {
    id: 'ap-roo-family',
    canonicalBrand: 'Audemars Piguet',
    family: 'Royal Oak Offshore',
    nicknames: [],
    aliases: ['ROO', 'Royal Oak Offshore', 'Offshore'],
  },
  {
    id: 'ap-panda',
    canonicalBrand: 'Audemars Piguet',
    family: 'Royal Oak Offshore',
    canonicalModel: 'Royal Oak Offshore Panda',
    nicknames: ['Panda'],
    aliases: ['AP Panda', 'ROO Panda'],
    ambiguousNickname: true,
  },
  {
    id: 'ap-vampire',
    canonicalBrand: 'Audemars Piguet',
    family: 'Royal Oak',
    nicknames: ['Vampire'],
    aliases: ['AP Vampire'],
  },
  {
    id: 'ap-ghost',
    canonicalBrand: 'Audemars Piguet',
    family: 'Royal Oak',
    nicknames: ['Ghost'],
    aliases: ['AP Ghost'],
    ambiguousNickname: true,
  },

  // ── Patek ───────────────────────────────────────────────────────────────
  {
    id: 'pp-nautilus',
    canonicalBrand: 'Patek Philippe',
    family: 'Nautilus',
    canonicalModel: 'Nautilus',
    references: ['5711', '5711/1A-010', '5811'],
    nicknames: [],
    aliases: ['PP Nautilus', 'Nautilus', 'Patek Nautilus'],
  },
  {
    id: 'pp-aquanaut',
    canonicalBrand: 'Patek Philippe',
    family: 'Aquanaut',
    canonicalModel: 'Aquanaut',
    references: ['5167', '5167A-001', '5168'],
    nicknames: [],
    aliases: ['PP Aquanaut', 'Aquanaut', 'Patek Aquanaut'],
  },
  {
    id: 'pp-tiffany',
    canonicalBrand: 'Patek Philippe',
    family: 'Nautilus',
    nicknames: ['Tiffany'],
    aliases: ['PP Tiffany', 'Tiffany Nautilus'],
    ambiguousNickname: true,
  },

  // ── Vacheron / Omega / others ───────────────────────────────────────────
  {
    id: 'vc-overseas',
    canonicalBrand: 'Vacheron Constantin',
    family: 'Overseas',
    canonicalModel: 'Overseas',
    nicknames: [],
    aliases: ['VC Overseas', 'Overseas', 'Vacheron Overseas'],
  },
  {
    id: 'omega-snoopy',
    canonicalBrand: 'Omega',
    family: 'Speedmaster',
    canonicalModel: 'Speedmaster Snoopy',
    references: ['310.32.42.50.02.001'],
    nicknames: ['Snoopy'],
    aliases: ['Omega Snoopy', 'Speedmaster Snoopy', 'Silver Snoopy'],
  },
  {
    id: 'omega-moonwatch',
    canonicalBrand: 'Omega',
    family: 'Speedmaster',
    canonicalModel: 'Speedmaster Professional Moonwatch',
    nicknames: ['Moonwatch'],
    aliases: ['Speedy', 'Speedmaster', 'Omega Moonwatch'],
  },
  {
    id: 'omega-ed-white',
    canonicalBrand: 'Omega',
    family: 'Speedmaster',
    canonicalModel: 'Speedmaster Ed White',
    nicknames: ['Ed White'],
    aliases: ['Omega Ed White'],
  },
  {
    id: 'tudor-panda',
    canonicalBrand: 'Tudor',
    family: 'Black Bay Chrono',
    nicknames: ['Panda'],
    aliases: ['Tudor Panda', 'Black Bay Panda'],
    ambiguousNickname: true,
  },
];

export const FAMILY_ALIASES: Array<{ family: string; tokens: string[]; brand?: string }> = [
  { family: 'GMT-Master II', tokens: ['gmt', 'gmt master', 'gmt-master', 'gmt-master ii', 'gmt master ii'] },
  { family: 'Daytona', tokens: ['daytona', 'cosmo', 'cosmograph'] },
  { family: 'Submariner', tokens: ['sub', 'submariner'] },
  { family: 'Royal Oak', tokens: ['ro', 'royal oak'], brand: 'Audemars Piguet' },
  { family: 'Royal Oak Offshore', tokens: ['roo', 'offshore', 'royal oak offshore'], brand: 'Audemars Piguet' },
  { family: 'Nautilus', tokens: ['nautilus'], brand: 'Patek Philippe' },
  { family: 'Aquanaut', tokens: ['aquanaut'], brand: 'Patek Philippe' },
  { family: 'Overseas', tokens: ['overseas'], brand: 'Vacheron Constantin' },
  { family: 'Speedmaster', tokens: ['speedmaster', 'speedy', 'moonwatch'] },
  { family: 'Santos', tokens: ['santos'], brand: 'Cartier' },
];
